# Generated by Django 4.2.6 on 2023-11-28 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tvapp', '0012_mensajechat_destacado_mensajechat_sticker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajechat',
            name='sticker',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
