# Generated by Django 4.2.6 on 2023-11-28 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tvapp', '0013_alter_mensajechat_sticker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sala',
            name='categoriaId',
        ),
        migrations.DeleteModel(
            name='MensajeChat',
        ),
        migrations.DeleteModel(
            name='Sala',
        ),
    ]
