# Generated by Django 5.0.4 on 2024-04-07 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tvapp', '0017_suscripcionusuario_delete_suscripcion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sala',
            name='categoriaId',
        ),
        migrations.RemoveField(
            model_name='mensajechat',
            name='sala',
        ),
        migrations.RemoveField(
            model_name='mensajechat',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='puntos',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='sala',
            name='creador',
        ),
        migrations.RemoveField(
            model_name='solespe',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='suscripcionusuario',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='suscripcionusuario',
            name='usuario_suscrito',
        ),
        migrations.RemoveField(
            model_name='tarjeta',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='MensajeChat',
        ),
        migrations.DeleteModel(
            name='Puntos',
        ),
        migrations.DeleteModel(
            name='Sala',
        ),
        migrations.DeleteModel(
            name='Solespe',
        ),
        migrations.DeleteModel(
            name='SuscripcionUsuario',
        ),
        migrations.DeleteModel(
            name='Tarjeta',
        ),
    ]
